### PR TITLE
Prefer XLSX plugin when reading XLSX files.

### PR DESCRIPTION
**Pull request by craiga**
Reading xlsx files with xlrd appears to be broken in Python 3.9.

```
    def process_stream(self, stream, heading=None):
        if self.verbosity >= 2 and heading is not None:
            fprintf(self.logfile, "\n=== %s ===\n", heading)
        self.tree = ET.parse(stream)
        getmethod = self.tag2meth.get
>       for elem in self.tree.iter() if Element_has_iter else self.tree.getiterator():
E       AttributeError: 'ElementTree' object has no attribute 'getiterator'
```

Reading xls files still works fine, but xlrd's XML parsing seems to rely on a method which has been removed from ElementTree. I haven't looked to far into this, but I did see this in [what's new in Python 3.9](https://docs.python.org/3.9/whatsnew/3.9.html):

> Methods getchildren() and getiterator() of classes ElementTree and Element in the ElementTree module have been removed. They were deprecated in Python 3.2. Use iter(x) or list(x) instead of x.getchildren() and x.iter() or list(x.iter()) instead of x.getiterator(). (Contributed by Serhiy Storchaka in bpo-36543.)

This means that I can't parse xlsx _and_ xls files under Python 3.9, as pyexcel-xls is preferred over pyexcel-xlsx.

This PR should resolve this, but I don't know what the knock-on effects of this might be.

What do you think?

- [ ] Has test cases written?
- [ ] Has all code lines tested?
- [ ] Has `make format` been run?
- [ ] Please update CHANGELOG.yml(not CHANGELOG.rst)
- [ ] Passes all Travis CI builds
- [ ] Has fair amount of documentation if your change is complex
- [ ] Agree on NEW BSD License for your contribution

### CODE REVIEW

**Comment by chfw** [comment]
Makes sense. 

Please update changelog.yml and tick on new bsd license box.

Thanks for adding 3.9-dev. If you want the change  stay, the right place(the strange place) is .moban.d/custom_travis.yml.jj2. Then our tool will render it as .travis.yml

**Comment by chfw** [comment]
Just a note: this change does not have material change rather the helper message put xlsx before xls. Inside pyexcel, there is no preference mechanism.

**Comment by chfw** [comment]
@craiga , what's your plan for this PR?

if you want to force pyexcel-io to use pyexcel-xlsx, you can pass on a parameter: "library=..".

**Comment by craiga** [comment]
@chfw As you mentioned, I've just verified that this change **doesn't** fix the issue I'm seeing in my app. I've been trying to replicate the problem in a test inside pyexcel-io without luck. I'm going to close this PR and do some more investigation.

**Comment by chfw** [comment]
Please use ‘library’ option to force it to use pyexcel-xlsx

**Comment by craiga** [comment]
@chfw That approach works, but unfortunately I can't see a good opportunity to specify a library when the file is uploaded using `django_excel`. I've logged this as an issue on that project https://github.com/pyexcel-webwares/django-excel/issues/66, and would love to hear your thoughts.

**Pull request closed without merging**
